### ISSUE TITLE
Implement query cache eviction

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#12905]

**Comment by ajcvickers** [comment]
See #12902, #8223

**Comment by ajcvickers** [comment]
Notes from discussion: we will use `MemoryCache` but fully internalized.

**Comment by AndriySvyryd** [comment]
We should consider using a simple heuristic to estimate the relative cache entry size (e.g. number of expressions in the tree).

**Comment by roji** [comment]
@AndriySvyryd when we do implement cache eviction, not sure we should try to track memory size as opposed to simply the number of queries cached... But we'll revisit...

**Comment by smitpatel** [comment]
For heuristic consider the cost of computing & usage count.

**Comment by NickCraver** [comment]
Unfortuntely, the changes in https://github.com/aspnet/EntityFrameworkCore/commit/67a200f68a1549d19560e9e6228daa411bd00a6c related to this issue are affecting other libraries. If EF Core is setup first (common) the rather low size limit added to the memory cache breaks things downstream, a la https://github.com/MiniProfiler/dotnet/issues/433 (breaking MiniProfiler's storage).

Has the impact of the startup race and the somewhat magical/hidden limits been considered here? I'm not sure the approach used is great for such a widely used service to be registered this way. Any thoughts on approaching this a different way?

**Comment by AndriySvyryd** [comment]
@NickCraver I thought this was fixed in https://github.com/aspnet/EntityFrameworkCore/commit/cbd28ff4871cc5abc626dc7b4917a0b20538e2f8#diff-1f53a7b867113cb4b9c61eccef38abd9L486, but that was a different change. This is definitely not the intended behavior.

**Comment by ajcvickers** [comment]
@NickCraver In 3.0, by default, the memory cache used by EF is independent of other memory cache instances precisely because of this issue. Concretely, this means `AddDbContext` no longer uses the memory cache setup by ASP.NET Core. However, the `UseMemoryCache` API still exists to optionally allow use of the same cache instance. Are you calling this? Is it necessary (or desired, within the limits of what `IMemoryCache` allows) to use the same cache for EF and other things?

Ideally, `IMemoryCache` would allow much better control over these kinds of things. However, the last time we revisited this with the ASP.NET team there was really no interest in going there.

**Comment by AndriySvyryd** [comment]
@ajcvickers I believe @NickCraver refers to the services added by the AddEntityFramework* methods. There are still ASP.NET apps that use them instead of just calling AddDbContext

**Comment by ajcvickers** [comment]
@NickCraver Are you calling `AddEntityFramework` or `AddEntityFrameworkSqlServer`? If so, for what reason?

**Comment by Cooksauce** [comment]
@ajcvickers The startup config which causes this issue is in the MiniProfiler issue he referenced. Specifically, this comment: [MiniProfiler/dotnet#433-547077949](https://github.com/MiniProfiler/dotnet/issues/433#issuecomment-547077949)

Are the `AddEntityFramework` methods not recommended? Is there documentation somewhere about why you would (or wouldn't) want to use them?

**Comment by ajcvickers** [comment]
@Cooksauce Yes, that is absolutely not recommended.

**Comment by AndriySvyryd** [comment]
Filed https://github.com/aspnet/EntityFrameworkCore/issues/19053 to help identifying this pattern.

**Comment by simeyla** [comment]
I've been quite confused about EF Core's usage of `IMemoryCache` [for literally years!](https://stackoverflow.com/questions/58406143/unexpected-cache-entry-must-specify-a-value-for-size-when-sizelimit-is-set-mes)

I had a call to `AddEntityFrameworkSqlServer()` in my startup because it seemed like something that should have been there. I've finally removed it today.

When it was there, it was calling the following (indirectly, as part of `TryAddCoreServices`):

    TryAdd<IMemoryCache>(_ => new MemoryCache(new MemoryCacheOptions { SizeLimit = 10240 }));

This 'breaks' usage of `IMemoryCache` elsewhere if you don't want to use a size limit.

So why I'm confused is that if the memory cache is now internal to EF Core (as mentioned by @ajcvickers in 2019) then why is a SizeLimit still set via `TryAdd` above? 

Is it just that since `AddEntityFrameworkSqlServer` is obsolete that this config is just being left untouched to avoid breaking changes?

**Comment by roji** [comment]
@simeyla first, the IMemoryCache in question here is in EF Core's internal service provider; this has nothing to do with any IMemoryCache that you register e.g. in your ASP.NET DI container. It only manages caching that's internal to EF, notably EF LINQ query caching. EF's internal service provider is an implementation detail and you should generally not be modifying or tweaking things there.

AddEntityFrameworkSqlServer() certainly isn't obsolete; it is used whenever you configure EF Core to use SQL Server via UseSqlServer(). It is almost never needed that you call this method directly (but in some edge cases it is), so you can also consider it an internal implementation detail.

Finally, it's generally a bad idea to not have a SizeLimit on caches. For example, if you remove the size limit on EF's internal IMemoryCache - which caches LINQ queries - that means it will grow in an unbounded way as more and more query shapes are executed, without ever evicting anything. That could result in the application consuming too much memory and eventually crashing.

The same logic applies to caching in other layers - you should generally always have a size limit. Why specifically are you attempting to remove it?

**Comment by simeyla** [comment]
My caching needs are pretty simple and I'm using [LazyCache](https://github.com/alastairtree/LazyCache) for simplicity. It sits on top of `IMemoryCache`. Point taken about the dangers of 'size-less' caches, but this is fine for my needs 😈

If I use `AddEntityFrameworkSqlServer()` explicitly I get the `Cache entry must specify a value for Size when SizeLimit is set.` error. 

> the IMemoryCache in question here is in EF Core's internal service provider; this has nothing to do with any IMemoryCache that you register e.g. in your ASP.NET DI container. 

I think this is the crux of my confusion, **because it *is* the same one!**

https://github.com/dotnet/efcore/blob/a76f27f3fa537f8d147966483c13aae834bf3772/src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs#L14

Then EF does `TryAdd()` for the global `Microsoft.Extensions.Caching.Memory.IMemoryCache` with a size:

https://github.com/dotnet/efcore/blob/a76f27f3fa537f8d147966483c13aae834bf3772/src/EFCore/Infrastructure/EntityFrameworkServicesBuilder.cs#L297

This explains why my [StackOverflow question](https://stackoverflow.com/questions/58406143/unexpected-cache-entry-must-specify-a-value-for-size-when-sizelimit-is-set-mes) has over 8k views - because so many people have run into the issue that EF Core is still using the global `IMemoryCache` and has set a size on it (even if core team members think it isn't using it!). 

I seem to be able to 'fix' LazyCache by just not calling `AddEntityFrameworkSqlServer()` and then in some kind of deterministic fluke it works. However it makes me wonder if EF Core is now using a size-less `IMemoryCache` that it could surely lead to memory overflow?

Thanks for your reply. It seems to either be a longstanding bug, a misunderstanding or something else!

**Comment by roji** [comment]
You are simply not supposed to call AddEntityFrameworkSqlServer() on your ASP.NET container - that configures all of EF's services on that container; the right way to use EF in almost all cases is to let it configure its own internal service provider. In other words, just call UseSqlServer() as indicated in all the tutorials, and EF will set up an internal DI service provider (completely distinct from the ASP.NET one), and will configure its own internal IMemoryCache there.

**Comment by kuldeepGDI** [comment]
> You are simply not supposed to call AddEntityFrameworkSqlServer() on your ASP.NET container - that configures all of EF's services on that container; the right way to use EF in almost all cases is to let it configure its own internal service provider. In other words, just call UseSqlServer() as indicated in all the tutorials, and EF will set up an internal DI service provider (completely distinct from the ASP.NET one), and will configure its own internal IMemoryCache there.

Is it possible somehow to limit the cache entries to lets say 1000 or somehow do cache eviction earlier ?  I notice that cache entries are going in Heap Generation 2 and and not cleaned up. This over the days is leading to OOM issues in memory constrained k3s environments i suspect.
