### ISSUE TITLE
EFCore Delete And Add will merge to Update，and throw concurrency Exception

### ISSUE THREAD

**Issue by Gavinluo** [aspnet/EntityFrameworkCore#16355]
i`m trying to update my code from ef6 to efcore . and get  a concurrency exception

i have a Demo Entity
```C#
 public class itemMap : IEntityTypeConfiguration<item>
    {
        public void Configure(EntityTypeBuilder<item> builder)
        {
            builder.HasKey(t => t.ItemGID);
            builder.Property(t => t.ItemGID)
                .IsRequired()
                .HasMaxLength(100);
            builder.Property(t => t.ItemID)
                .IsRequired()
                .HasMaxLength(100);
            builder.ToTable("item");
            builder.Property(t => t.ItemGID).HasColumnName("ItemGID");
            builder.Property(t => t.ItemID).HasColumnName("ItemID");
            builder.Property(t => t.TS)
                    .ValueGeneratedOnUpdate().IsConcurrencyToken();
        }
    }
```

DemoCode:

```C#
            using (var context = new demoContext())
            {
                var defaultPrimaryKey = "test";
                var data = context.Set<item>().Find(defaultPrimaryKey);
                context.Set<item>().Remove(data);
                var item1 = new item
                {
                    ItemGID = defaultPrimaryKey,ItemID = defaultPrimaryKey,
                    TS = DateTime.Now
                };
                context.Set<item>().Add(item1);
                context.SaveChanges();
            }
```

this scene is when you call Set<T>.Remove  and then call Set<T>.Add , and the entity primary key is same .
    1. EFCore  SaveChange will transfer to one update sql.
    2. EF6 SaveChange will transfer to two sql，one is delete sql and another is insert sql.
will , this is smart for EFCore ,but with ConcurrencyToken property , the problem is the update sql where condition TS is 'NewValue' not DatabaseValue , so get a concurrency exception.
i think if efcore merge delete and insert to update , the ConcurrencyToken property value will use databaseValue , not the insert new value ? 
   i had tested on sqlserver , and even get this error , so it is not problem for provider .
```
Exception message:
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException:“Database operation expected to affect 1 row(s) but actually affected 0 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.”
```

```
LogSql is :   Executed DbCommand (2ms) [Parameters=[@p3='test' (Nullable = false) (Size = 100), @p0='' (Size = 100), @p4='test' (Nullable = false) (Size = 100), @p1='' (Size = 100), @p2='2019-06-29T14:59:15' (DbType = DateTime), @p5='2019-06-29T14:59:15' (DbType = DateTime)], CommandType='Text', CommandTimeout='30']
UPDATE `item` SET `ItemDesc` = @p0, `ItemName` = @p1, `TS` = @p2
WHERE `ItemGID` = @p3 AND `ItemID` = @p4 AND `TS` = @p5;
SELECT ROW_COUNT();
```
@p5 is insert new value , so affected 0 row(s). if @p5 is databaseValue they will be ok. 

### Further technical details
EF Core version:
Microsoft.EntityFrameworkCore 2.2.4
Database Provider: Pomelo.EntityFrameworkCore.MySql 2.2
Operating system: Windows 10
IDE: (e.g. Visual Studio 2019 16.1.3)

**Comment by Gavinluo** [comment]
this is demo code
https://github.com/Gavinluo/EFCoreSameKeyException

**Comment by ajcvickers** [comment]
Note for triage: this looks like an issue with the implementation for #7340
/cc @AndriySvyryd

**Comment by AndriySvyryd** [comment]
This might be already fixed in 3.0.0-preview5

**Comment by Gavinluo** [comment]
@AndriySvyryd @ajcvickers   good job , I have already tested it on 3.0.0-preview6 and it works . but my project is work on netcore 2.2 ,  do you have a plan ？ how should i to do with this problem?

**Comment by ajcvickers** [comment]
@Gavinluo The usual workaround is to make two calls to `SaveChanges`--one to do the remove, one to do the add.

**Comment by Gavinluo** [comment]
thanks @ajcvickers , that works , and make sure the twice ``SaveChanges`` in same transaction , must create a transaction around this.  our project more than two million code , and the migration to net core is planned for Sep. 
Can I wait until you fix this issue in net core 2.0 before migrating?

**Comment by ajcvickers** [comment]
@Gavinluo I'm not really following your last question. This is fixed for EF Core 3.0, but there are no plans to bring that to .NET Core 2.0.

**Comment by Gavinluo** [comment]
@ajcvickers thks, .NET Core 3.0 not release, and  i wana use it in .NET Core 2.0 , i`m very disappointed to see that

**Comment by douglasg14b** [comment]
Odd that this is shown as fixes in 3.0

I'm on 3.1 and experiencing this issue. I have 1 deleted entry, and 1 added entry and EF Core 3.1 sends an update instead which results in a `Database operation expected to affect 1 row(s) but actually affected 0 row(s)` exception.

**Comment by asulwer** [comment]
this is still occurring in Core 5.0.7.  maybe these programmers should check their code before they say its working?

**Comment by AndriySvyryd** [comment]
@asulwer Please open a new issue and include a small repro project, if possible targeting SQL Server or SQLite

**Comment by asulwer** [comment]
> @asulwer Please open a new issue and include a small repro project, if possible targeting SQL Server or SQLite

this is normal procedure for new bugs but not existing bugs that were reported as being fixed.  it was reported here and this one needs to be reopened.

fyi: my example would be the same as this one.  Remove, Add, SaveChanges, causes the error

**Comment by AndriySvyryd** [comment]
@asulwer I verified that the repro in https://github.com/Gavinluo/EFCoreSameKeyException doesn't throw exceptions on 3.1.16 or 5.0.7

**Comment by asulwer** [comment]
> @asulwer I verified that the repro in https://github.com/Gavinluo/EFCoreSameKeyException doesn't throw exceptions on 3.1.16 or 5.0.7 for SQL Server

you are wrong, i just tested this and it failed with

![image](https://user-images.githubusercontent.com/7673412/122114084-bc8dbb80-cdd7-11eb-9200-35a92304745b.png)

**Comment by AndriySvyryd** [comment]
@asulwer Did you change the provider to SQL Server when you ran that code?

If it only fails with the Pomelo provider you need to report the issue to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by asulwer** [comment]
that code contains a file itemMap.cs in the Configure method

```
builder.Property(t => t.ItemID).HasColumnName("ItemID").IsConcurrencyToken();
builder.Property(t => t.TS).ValueGeneratedOnUpdate().IsConcurrencyToken();
```

removing IsConcurrencyToken() solved the problem, for this code

**Comment by asulwer** [comment]
> @asulwer Did you change the provider to SQL Server when you ran that code?
> 
> If it only fails with the Pomelo provider you need to report the issue to https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

i changed to MsSql provider.  i reworked the code and was able to eliminate the issue.

[https://github.com/asulwer/EFCore_Exception](url)
